import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Sidebar from "@/ui/Sidebar"
import Navbar from "@/ui/Navbar";

const openSans = Open_Sans({
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} antialiased flex min-h-[100vh]`}
      >
        <Sidebar />
        <div className="flex-1 flex flex-col items-center" style={{
          height: "100vh",
        }}>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
